# PATH variables must be set in .env files.
services:
  api:  # Start api service first so mcp service doesn't 404 when it tries to fetch jwks.json.
    build:
      context: ${PATHS_PROJECT_DIR}
      dockerfile: backend/Dockerfile.api
    command: >
      /bin/sh -c "set -e &&
      python -m alembic upgrade head &&
      python src/mcp_demo/entries/fastapi_app.py"
    container_name: api-dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Re-use the same values that the FastAPI app expects.
      - PATHS_PROJECT_DIR=/usr
      - PATHS_SECRETS_DIR=/usr/secrets
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:8000/auth/jwks.json >/dev/null || exit 1"]
      interval: 10s
      retries: 3
      timeout: 5s
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"  # Expose POST /auth/token and GET /auth/jwks.json
    volumes:
      - ${PATHS_PROJECT_DIR}/backend:/usr/backend
      - venv_api:/usr/backend/.venv
  caddy:
    container_name: caddy-dev
    depends_on:
      api:
        condition: service_healthy
      mcp:
        condition: service_started
    env_file:
      - .env
      - ${PATHS_PROJECT_DIR}/.env
    image: "${DOCKER_CADDY_IMAGE}"
    ports:
      - "${CADDY_HTTP_PORT}:${CADDY_HTTP_PORT}"
      - "${CADDY_HTTPS_PORT}:${CADDY_HTTPS_PORT}"
      - "${CADDY_UDP_PORT}:${CADDY_UDP_PORT}/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
  postgres:
    container_name: postgres-dev
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 3
      timeout: 5s
    image: "${DOCKER_PG_VECTOR_IMAGE}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mcp:
    build:
      context: ${PATHS_PROJECT_DIR}
      dockerfile: backend/Dockerfile.mcp
    command: >
      /bin/sh -c "set -e &&
      python -m alembic upgrade head &&
      python src/mcp_demo/entries/mcp_server_main.py"
    container_name: mcp-dev
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PATHS_PROJECT_DIR=/usr
      - PATHS_SECRETS_DIR=/usr/secrets
    ports:
      - "${FASTMCP_PORT}:${FASTMCP_PORT}"
    volumes:
      - ${PATHS_PROJECT_DIR}/backend:/usr/backend
      - venv_mcp:/usr/backend/.venv
  redis:
    container_name: redis-dev
    env_file:
      - .env
    image: "${DOCKER_REDIS_IMAGE}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    volumes:
      - redis_data:/redis_data
volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  redis_data:
  venv_api:
  venv_mcp:
