"""Initial migration.

Revision ID: 88cffe96023d
Revises:
Create Date: 2025-07-14 12:22:05.336131

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88cffe96023d"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("secret_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "updated_datetime_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(secret_hash) > 50",
            name=op.f("ck_client_chk_client_secret_hash_len"),
        ),
        sa.PrimaryKeyConstraint("client_id", name=op.f("pk_client")),
    )
    op.create_table(
        "scope",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_scope")),
    )
    op.create_table(
        "user",
        sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("recovery_codes_hash", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "updated_datetime_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(password_hash) > 50",
            name=op.f("ck_user_chk_user_password_hash_len"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "user_scope",
        sa.Column("scope_name", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scope_name"], ["scope.name"], name=op.f("fk_user_scope_scope_name_scope")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], name=op.f("fk_user_scope_user_id_user")
        ),
        sa.PrimaryKeyConstraint("scope_name", "user_id", name=op.f("pk_user_scope")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_scope")
    op.drop_table("user")
    op.drop_table("scope")
    op.drop_table("client")
    # ### end Alembic commands ###
