"""Adding PKCE flow.

Revision ID: ba8193b2d728
Revises: 7deb7c653fe3
Create Date: 2025-07-27 13:56:29.804877

"""

# Standard Library
from typing import Sequence, Union

# Third Party Library
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba8193b2d728"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "7deb7c653fe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "allowed_code_challenge_methods",
            sa.ARRAY(sa.String()),
            server_default="{S256}",
            nullable=False,
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "pkce_enforced",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "client", sa.Column("redirect_uris", sa.ARRAY(sa.String()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "redirect_uris")
    op.drop_column("client", "pkce_enforced")
    op.drop_column("client", "allowed_code_challenge_methods")
    # ### end Alembic commands ###
